//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteVisitAW
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> FillDateTime { get; set; }
        public string AWSDataLoggerGSMSerialNumber { get; set; }
        public string AirTemperatureHumiditySerialNumber { get; set; }
        public string WindSpeedWindDirectionSerialNumber { get; set; }
        public string ATMSerialNumber { get; set; }
        public string SolarRadiationSerialNumber { get; set; }
        public string TrippingBucketSerialNumber { get; set; }
        public string PanEvaporationSerialNumber { get; set; }
        public string AHBatterySerialNumber { get; set; }
        public string SolarPanelSerialNumber { get; set; }
        public string UHFSatelliteSerialNumber { get; set; }
        public string EnclosureSerialNumber { get; set; }
        public string YagiAntennaSerialNumber { get; set; }
        public string Temperature { get; set; }
        public string RH { get; set; }
        public string WindSpeed { get; set; }
        public string WindDirection { get; set; }
        public string SolarRadiation { get; set; }
        public string ATMPressure { get; set; }
        public string RainFall { get; set; }
        public string PanEvaporation { get; set; }
        public string BatteryVoltage { get; set; }
        public string SolarPanelVoltage { get; set; }
        public string SystemDateTime { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string AWSSolarPanelCleaning { get; set; }
        public string AWSEnclosureCleaning { get; set; }
        public string ATRHSensorSiteCleaning { get; set; }
        public string SolarRadiationSiteCleaning { get; set; }
        public string RainGaugeSiteCleaning { get; set; }
        public string WindspeedDirectionSiteCleaning { get; set; }
        public string AWSSiteSiteCleaning { get; set; }
        public string BeforeCheckListAWSDataLoggerGSM { get; set; }
        public string BeforeCheckListAirTempHumidity { get; set; }
        public string BeforeCheckListWindSpeedDirection { get; set; }
        public string BeforeCheckListATMP { get; set; }
        public string BeforeCheckListSolarRadiation { get; set; }
        public string BeforeCheckListTippingBucket { get; set; }
        public string BeforeCheckListPanEvaporation { get; set; }
        public string BeforeCheckListBatteryAWS { get; set; }
        public string BeforeCheckListSolarPanelAWS { get; set; }
        public string BeforeCheckListUHFAWS { get; set; }
        public string BeforeCheckListSolarBatteryCharger { get; set; }
        public string BeforeCheckListEnclosureAWS { get; set; }
        public string BeforeCheckListYagiAntenaAWS { get; set; }
        public string BeforeCheckListAWSFencing { get; set; }
        public string BeforeCheckListGPRSDataAWS { get; set; }
        public string BeforeCheckListINSATDataAWS { get; set; }
        public string AfterCheckListAWSDataLoggerGSM { get; set; }
        public string AfterCheckListAirTempHumidity { get; set; }
        public string AfterCheckListWindSpeedDirection { get; set; }
        public string AfterCheckListATMP { get; set; }
        public string AfterCheckListSolarRadiation { get; set; }
        public string AfterCheckListTippingBucket { get; set; }
        public string AfterCheckListPanEvaporation { get; set; }
        public string AfterCheckListBatteryAWS { get; set; }
        public string AfterCheckListSolarPanelAWS { get; set; }
        public string AfterCheckListUHFAWS { get; set; }
        public string AfterheckListSolarBatteryCharger { get; set; }
        public string AfterCheckListEnclosureAWS { get; set; }
        public string AfterCheckListYagiAntenaAWS { get; set; }
        public string AfterCheckListAWSFencing { get; set; }
        public string AfterCheckListGPRSDataAWS { get; set; }
        public string AfterCheckListINSATDataAWS { get; set; }
        public string RemarksCheckListAWSDataLoggerGSM { get; set; }
        public string RemarksCheckListAirTempHumidity { get; set; }
        public string RemarksCheckListWindSpeedDirection { get; set; }
        public string RemarksCheckListATMP { get; set; }
        public string RemarksCheckListSolarRadiation { get; set; }
        public string RemarksCheckListTippingBucket { get; set; }
        public string RemarksCheckListPanEvaporation { get; set; }
        public string RemarksCheckListBatteryAWS { get; set; }
        public string RemarksCheckListSolarPanelAWS { get; set; }
        public string RemarksCheckListUHFAWS { get; set; }
        public string RemarksheckListSolarBatteryCharger { get; set; }
        public string RemarksCheckListEnclosureAWS { get; set; }
        public string RemarksCheckListYagiAntenaAWS { get; set; }
        public string RemarksCheckListAWSFencing { get; set; }
        public string RemarksCheckListGPRSDataAWS { get; set; }
        public string RemarksCheckListINSATDataAWS { get; set; }
        public string AzistaName { get; set; }
        public string AzistaDesignation { get; set; }
        public string AzistaSignature { get; set; }
        public string SiteInChargeName { get; set; }
        public string SiteInChargeDesignation { get; set; }
        public string SiteInChargeContactNumber { get; set; }
        public string SiteInChargeSignature { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
