//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminMenu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string Controller { get; set; }
        public string ViewName { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
