//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FTPDetails
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FTPUrl { get; set; }
        public string ActualPath { get; set; }
        public string BackupPath { get; set; }
        public System.DateTime ScheduleAt { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsRunning { get; set; }
    }
}
