//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstallationFormLevel5
    {
        public int ID { get; set; }
        public Nullable<int> Level1ID { get; set; }
        public string StationInchargeName { get; set; }
        public string ContactDetailM { get; set; }
        public string StationKeysSubmitedPerson { get; set; }
        public string ContactDetail { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
