//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VMCRainDetail
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string RainUnit { get; set; }
        public string CurrentDay { get; set; }
        public string LastDay { get; set; }
        public string Last24HR { get; set; }
        public string Last15Min { get; set; }
        public string LastHour { get; set; }
        public string CurrentRainRate { get; set; }
        public string StormValue { get; set; }
        public string StormUnit { get; set; }
        public string StormStartDateTime { get; set; }
        public string StormDuration { get; set; }
        public string MonthTotal { get; set; }
        public string YearTotal { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
