//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteVisit2_AWSStationPhotographs
    {
        public int ID { get; set; }
        public Nullable<int> GeneralInformationID { get; set; }
        public Nullable<int> SystemParameterID { get; set; }
        public string TypesOfPhotographs { get; set; }
        public string PhotoStatus { get; set; }
    }
}
