//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_RJSW2NHP061
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Mobile { get; set; }
        public string Battery_Voltage { get; set; }
        public string Water_Level { get; set; }
        public string Hourly_Rainfall { get; set; }
        public string Daily_Rain { get; set; }
        public string Air_Temperature { get; set; }
        public string Snow_Depth { get; set; }
        public string Evaporation { get; set; }
        public string Wind_Speed { get; set; }
        public string Wind_Direction { get; set; }
        public string Atmospheric_Pressure { get; set; }
        public string Relative_Humidity { get; set; }
        public string Solar_Radiation { get; set; }
        public string Peripheral_Status { get; set; }
        public string Status { get; set; }
        public string Created_Date { get; set; }
    }
}
