//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HealthReport
    {
        public int ID { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string StationType { get; set; }
        public Nullable<int> DataReceived { get; set; }
        public Nullable<decimal> PercentageOfData { get; set; }
        public string UserID { get; set; }
    }
}
