//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Replacement
    {
        public int ID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public string Spares { get; set; }
        public string Oldserialno { get; set; }
        public string Newserialno { get; set; }
        public string ReasonforReplacement { get; set; }
    }
}
