//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_33
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string BuoyName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Sea_Surface_Temperature { get; set; }
        public string Barometric_pressure_sensor { get; set; }
        public string Battery_Voltage { get; set; }
    }
}
