//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransmissionConfigruation
    {
        public int ID { get; set; }
        public string Channel_Number { get; set; }
        public string Identification_Code { get; set; }
        public string Parameter { get; set; }
        public string Type { get; set; }
        public string Equition { get; set; }
        public string Columncount { get; set; }
    }
}
