//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteVisit2_AWSGeneralInformation
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string FillDate { get; set; }
        public string FillTime { get; set; }
        public string Division { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string altitude { get; set; }
        public string visittype { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
