//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeatherCollectionData
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string alt_m { get; set; }
        public string alt_ft { get; set; }
        public string wx_desc { get; set; }
        public string wx_code { get; set; }
        public string wx_icon { get; set; }
        public string temp_c { get; set; }
        public string temp_f { get; set; }
        public string feelslike_c { get; set; }
        public string feelslike_f { get; set; }
        public string humid_pct { get; set; }
        public string windspd_mph { get; set; }
        public string windspd_kmh { get; set; }
        public string windspd_kts { get; set; }
        public string windspd_ms { get; set; }
        public string winddir_deg { get; set; }
        public string winddir_compass { get; set; }
        public string cloudtotal_pct { get; set; }
        public string vis_km { get; set; }
        public string vis_mi { get; set; }
        public string vis_desc { get; set; }
        public string slp_mb { get; set; }
        public string slp_in { get; set; }
        public string dewpoint_c { get; set; }
        public string dewpoint_f { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Time { get; set; }
    }
}
