//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BatchLog_NA
    {
        public int ID { get; set; }
        public Nullable<int> AuditLogID { get; set; }
        public string FileName { get; set; }
        public string Data { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
