//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentReport
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Name { get; set; }
        public string Division { get; set; }
        public Nullable<int> ExpectedCount { get; set; }
        public Nullable<int> GPRS_Received { get; set; }
        public Nullable<decimal> GPRS_Percentage { get; set; }
        public Nullable<int> INSAT_Received { get; set; }
        public Nullable<decimal> INSAT_Percentage { get; set; }
        public Nullable<int> RecivedCount { get; set; }
        public Nullable<int> MissingCount { get; set; }
        public Nullable<decimal> Total_Percentage { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
