//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TestVMCDataReport
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Battery_Voltage__V_ { get; set; }
        public string Hourly_Rainfall__mm_ { get; set; }
        public string Daily_Rain__mm_ { get; set; }
        public string Air_Temperature__C_ { get; set; }
        public string Wind_Speed__m_s_ { get; set; }
        public string Wind_Direction__DEG_ { get; set; }
        public string Atmospheric_Pressure__hPa_ { get; set; }
        public string Humidity____ { get; set; }
        public string Dew_Point___C_ { get; set; }
        public string Wind_Run__m_ { get; set; }
        public string Wind_Chill__kgcal_m_2_h_ { get; set; }
        public string Heat_Index___C_ { get; set; }
        public string THW_Index___C_ { get; set; }
        public string Rain_Rate__mm_hr_ { get; set; }
        public string High_Speed__m_s_ { get; set; }
        public string High_Direction__Deg_ { get; set; }
    }
}
