//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteVisti2_AWSBackupFile
    {
        public int ID { get; set; }
        public Nullable<int> GeneralInformationID { get; set; }
        public Nullable<int> BackupID { get; set; }
        public string BackupStatus { get; set; }
    }
}
