//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HealthReport_GPRS_INSAT_Rec
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Name { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ExpectedCount { get; set; }
        public Nullable<int> GPRSReceived { get; set; }
        public Nullable<decimal> GPRSPercentage { get; set; }
        public Nullable<int> INSATReceived { get; set; }
        public Nullable<decimal> INSATPercentage { get; set; }
        public Nullable<int> RecivedCount { get; set; }
        public Nullable<int> MissingCount { get; set; }
        public Nullable<decimal> TotalPercentage { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
