//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FTPRawData
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string RawData { get; set; }
        public string Status { get; set; }
        public string Created_Date { get; set; }
    }
}
