//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_53
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Sea_Surface_Temperature { get; set; }
        public string Azista_Pressure_Sensor { get; set; }
        public string Vaisala_Pressure_Sensor { get; set; }
        public string Relative_Humidity { get; set; }
        public string Age { get; set; }
        public string Battery_Voltage { get; set; }
    }
}
