//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.Areas.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstallationFormLevel1
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string StationName { get; set; }
        public string StationAddress { get; set; }
        public string Pincode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Altitude { get; set; }
        public string SiteCondition { get; set; }
        public string SiteConditionRemarks { get; set; }
        public string SitePreparation { get; set; }
        public string SitePhotosTakenBefore { get; set; }
        public string SitePhotosTakenAfter { get; set; }
        public string MastFoundattion { get; set; }
        public string Installation { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
