//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTime_NA
    {
        public int TimeKey { get; set; }
        public int TimeAltKey { get; set; }
        public string Time30 { get; set; }
        public byte Hour30 { get; set; }
        public byte MinuteNumber { get; set; }
        public byte SecondNumber { get; set; }
        public int TimeInSecond { get; set; }
        public string HourlyBucket { get; set; }
        public int DayTimeBucketGroupKey { get; set; }
        public string DayTimeBucket { get; set; }
    }
}
