//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSurveyAWLRSiteSelection
    {
        public int ID { get; set; }
        public int GeneralInformationID { get; set; }
        public string SiteSize { get; set; }
        public string LandType { get; set; }
        public Nullable<bool> ElectromagneticInterface { get; set; }
        public Nullable<bool> UndergroundObstructions { get; set; }
        public Nullable<bool> AwayFromHighTensions { get; set; }
        public Nullable<bool> FreeFromShadow { get; set; }
        public string RadarMinimumMaxDistance { get; set; }
        public string WaterMaximumMaxDistance { get; set; }
        public string DistanceDataLoggerWaterLevel { get; set; }
        public string FencingSpace { get; set; }
        public Nullable<bool> StaffGauge { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
