//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSurveyGeneralInformation
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerEmailID { get; set; }
        public string InChargeName { get; set; }
        public string InChargeContact { get; set; }
        public string InChargeAddress { get; set; }
        public string InChargeEmailID { get; set; }
        public string SiteAccessibilityTime { get; set; }
        public string ProcedureToFollow { get; set; }
        public Nullable<bool> AccomodationFacility { get; set; }
        public Nullable<bool> TransportationFromNearBy { get; set; }
        public Nullable<bool> WeatherSiteCleaning { get; set; }
        public string LodgingBoardingFacility { get; set; }
        public string NearbyATM { get; set; }
        public string NearbyCityWithDistance { get; set; }
        public string LocalLanguage { get; set; }
        public string Photos1 { get; set; }
        public string Photos2 { get; set; }
        public string Photos3 { get; set; }
        public string Photos4 { get; set; }
        public string LaborAvailability { get; set; }
        public string CivilMaterialAvailability { get; set; }
        public Nullable<bool> CleanPath { get; set; }
        public string MountingLocation { get; set; }
        public string GSMNetwork { get; set; }
        public string Distance230VACPoint { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
