//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteVisitAWLR
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> FillDateTime { get; set; }
        public string DataLoggerGSMSerialNumber { get; set; }
        public string AWLRSensorSerialNumber { get; set; }
        public string BatterySerialNumber { get; set; }
        public string SolarPanelSerialNumber { get; set; }
        public string UHFSerialNumber { get; set; }
        public string Enclosure { get; set; }
        public string CrossedYagiAntenna { get; set; }
        public string WaterLevel { get; set; }
        public string BatteryVoltage { get; set; }
        public string SolarPanelVolatage { get; set; }
        public string SystemDateTime { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string SolarPanelCleaning { get; set; }
        public string EnclosureCleaning { get; set; }
        public string AWLRSiteCleaning { get; set; }
        public string BeforeCheckListDataLoggerGSM { get; set; }
        public string BeforeCheckListAWLRSensor { get; set; }
        public string BeforeCheckListBattery { get; set; }
        public string BeforeCheckListSolarPanel { get; set; }
        public string BeforeCheckListUHF { get; set; }
        public string BeforeCheckListEnclosure { get; set; }
        public string BeforeCheckListYagiAntena { get; set; }
        public string BeforeCheckListSolar { get; set; }
        public string BeforeCheckListAWLRCabin { get; set; }
        public string BeforeCheckListGPRSData { get; set; }
        public string BeforeCheckListINSATData { get; set; }
        public string AfterCheckListDataLoggerGSM { get; set; }
        public string AfterCheckListAWLRSensor { get; set; }
        public string AfterCheckListBattery { get; set; }
        public string AfterCheckListSolarPanel { get; set; }
        public string AfterCheckListUHF { get; set; }
        public string AfterCheckListEnclosure { get; set; }
        public string AfterCheckListYagiAntena { get; set; }
        public string AfterCheckListSolar { get; set; }
        public string AfterCheckListAWLRCabin { get; set; }
        public string AfterCheckListGPRSData { get; set; }
        public string AfterCheckListINSATData { get; set; }
        public string RemarksCheckListDataLoggerGSM { get; set; }
        public string RemarksCheckListAWLRSensor { get; set; }
        public string RemarksCheckListBattery { get; set; }
        public string RemarksCheckListSolarPanel { get; set; }
        public string RemarksCheckListUHF { get; set; }
        public string RemarksCheckListEnclosure { get; set; }
        public string RemarksCheckListYagiAntena { get; set; }
        public string RemarksCheckListSolar { get; set; }
        public string RemarksCheckListAWLRCabin { get; set; }
        public string RemarksCheckListGPRSData { get; set; }
        public string RemarksCheckListINSATData { get; set; }
        public string AzistaName { get; set; }
        public string AzistaDesignation { get; set; }
        public string AzistaSignature { get; set; }
        public string SiteInChargeName { get; set; }
        public string SiteInChargeDesignation { get; set; }
        public string SiteInChargeContactNumber { get; set; }
        public string SiteInChargeSignature { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
