//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystem
    {
        public int ID { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string StationType { get; set; }
        public string ModificationDate { get; set; }
        public string DataLogger { get; set; }
        public string FirmWare { get; set; }
        public string SimcardIssue { get; set; }
        public string JioUpgradation { get; set; }
        public string SignalStrength { get; set; }
        public string GprsAntenna { get; set; }
        public string IDF { get; set; }
        public string IDFFirmware { get; set; }
        public string UHFSateliteTrans { get; set; }
        public string UHFSateliteTransFirm { get; set; }
        public string CrossedYagiAntenna { get; set; }
        public string V12AH100Battery { get; set; }
        public string V12W40SolarPanel { get; set; }
        public string SolarCharger { get; set; }
        public string ATRHSensor { get; set; }
        public string WSWDSensor { get; set; }
        public string AtmPressure { get; set; }
        public string SolarRadiation { get; set; }
        public string RainSensor { get; set; }
        public string PanEvaporation { get; set; }
        public string AWLRSensor { get; set; }
        public string LastVisitedDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
