//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_GFD00004
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Station_Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Altitude { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Battery_Voltage { get; set; }
        public string GPS { get; set; }
        public string GPRS_SIGNALSTRENGTH { get; set; }
        public string TypeOfSystem { get; set; }
        public string NoOfParameters { get; set; }
        public string RainFall_HealthStatus { get; set; }
        public string Hourly_Rainfall { get; set; }
        public string Daily_Rain { get; set; }
        public string AirTemperature_HealthStatus { get; set; }
        public string Air_Temperature { get; set; }
        public string Temperature_Minimum { get; set; }
        public string Temperature_Maximum { get; set; }
        public string Temperature_DayMinMax { get; set; }
        public string Humidity_HealthStatus { get; set; }
        public string Humidity { get; set; }
        public string Humidity_Minimum { get; set; }
        public string Humidity_Maximum { get; set; }
        public string Humidity_DayMinMax { get; set; }
        public string WindDirection_HealthStatus10m { get; set; }
        public string WindDirection_10m { get; set; }
        public string WindSpeed_HealthStatus10m { get; set; }
        public string WindSpeed_10m1minAvg { get; set; }
        public string WindSpeed_10m3minAvg { get; set; }
        public string WindSpeed_10m10minAvg { get; set; }
        public string MaxWindSpeed_10m { get; set; }
        public string WindSpeed_DayMax10m { get; set; }
        public string Pressure_HealthStatus { get; set; }
        public string Atmospheric_Pressure { get; set; }
        public string WindDirection_HealthStatus3m { get; set; }
        public string WindDirection_3m { get; set; }
        public string WindSpeed_HealthStatus3m { get; set; }
        public string WindSpeed_3m1minAvg { get; set; }
        public string WindSpeed_3m3minAvg { get; set; }
        public string WindSpeed_3m10minAvg { get; set; }
        public string MaxWindSpeed_3m { get; set; }
        public string WindSpeed_DayMax3m { get; set; }
        public string SoilTemperature_HealthStatus10cm { get; set; }
        public string SoilTemperature_10cm { get; set; }
        public string SoilMoisture_HealthStatus10cm { get; set; }
        public string SoilMoisture_10cm { get; set; }
        public string SoilTemperature_HealthStatus30cm { get; set; }
        public string SoilTemperature_30cm { get; set; }
        public string SoilMoisture_HealthStatus30cm { get; set; }
        public string SoilMoisture_30cm { get; set; }
        public string SoilTemperature_HealthStatus70cm { get; set; }
        public string SoilTemperature_70cm { get; set; }
        public string SoilMoisture_HealthStatus70cm { get; set; }
        public string SoilMoisture_70cm { get; set; }
        public string SoilTemperature_HealthStatus100cm { get; set; }
        public string SoilTemperature_100cm { get; set; }
        public string SoilMoisture_HealthStatus100cm { get; set; }
        public string SoilMoisture_100cm { get; set; }
        public string SolarRadiation_HealthStatus { get; set; }
        public string Sunshine_Duration { get; set; }
        public string Global_Radiation { get; set; }
        public string Radiation_HealthStatus { get; set; }
        public string Par_Data { get; set; }
        public string Evaporameter_HealthStatus { get; set; }
        public string Evaporameter { get; set; }
        public string UVRadiation_a_HealthStatus { get; set; }
        public string UV_Radiation_a { get; set; }
        public string UVRadiation_b_HealthStatus { get; set; }
        public string UV_Radiation_b { get; set; }
        public string UV_Index { get; set; }
        public string VisibilitySensor_HealthStatus { get; set; }
        public string Visibility { get; set; }
        public string SnowDepth_HealthStatus { get; set; }
        public string Snow_Depth { get; set; }
        public string SnowWater_HealthStatus { get; set; }
        public string Snow_WaterEquivalent { get; set; }
        public string WaterLevel_HealthStatus { get; set; }
        public string WaterLevel_Measurement { get; set; }
        public string Status { get; set; }
        public string Created_Date { get; set; }
    }
}
