//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StieVisit2_AWLRGeneralInformation1
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string FillDate { get; set; }
        public string FillTime { get; set; }
        public string Division { get; set; }
        public string CabinLatitude { get; set; }
        public string CabinLongitude { get; set; }
        public string SensorLatitude { get; set; }
        public string SensorLongitude { get; set; }
        public string VisitType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CratedeDate { get; set; }
    }
}
