//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstallationFormLevel4
    {
        public int ID { get; set; }
        public Nullable<int> Level1ID { get; set; }
        public string DescriptionOfWork { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
