//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RainStorm
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string StormRate { get; set; }
        public string StormDateTime { get; set; }
        public string StormDuration { get; set; }
    }
}
