//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SensorParameterTemp
    {
        public int ID { get; set; }
        public Nullable<int> SensorParameterID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> ParameterID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
