//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NMS_NPCIL
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Wind_Speed_10m_Avg__m_s_ { get; set; }
        public string Wind_Speed_10m_Min__m_s_ { get; set; }
        public string Wind_Speed_10m_Max__m_s_ { get; set; }
        public string Wind_Direction_10m_Avg__Deg_ { get; set; }
        public string Wind_Speed_20m_Avg__m_s_ { get; set; }
        public string Wind_Speed__20m_Min__m_s_ { get; set; }
        public string Wind_Speed__20m_Max__m_s_ { get; set; }
        public string Wind_Direction_20m_Avg__Deg_ { get; set; }
        public string Wind_Speed_30m_Avg__m_s_ { get; set; }
        public string Wind_Speed_30m_Min__m_s_ { get; set; }
        public string Wind_Speed_30m_Max__m_s_ { get; set; }
        public string Wind_Direction_30m_Avg__Deg_ { get; set; }
        public string Air_Temperature_1_2m_Avg__C_ { get; set; }
        public string Air_Temperature_1_2m_Min__C_ { get; set; }
        public string Air_Temperature_1_2m_Max__C_ { get; set; }
        public string Air_Temperature_30m_Avg__C_ { get; set; }
        public string Air_Temperature_30m_Min__C_ { get; set; }
        public string Air_Temperature_30m_Max__C_ { get; set; }
        public string Relative_Humidity_1_2m_Avg____ { get; set; }
        public string Relative_Humidity_1_2m_Min____ { get; set; }
        public string Relative_Humidity_1_2m_Max____ { get; set; }
        public string Battery_Voltage__V_ { get; set; }
        public string Peripheral_Status { get; set; }
    }
}
