//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteVisit2_AWSOtherInformation1
    {
        public int ID { get; set; }
        public Nullable<int> GeneralInformationID { get; set; }
        public string PurposeOfVisit { get; set; }
        public string OtherObservation { get; set; }
        public string ActionTaken { get; set; }
        public string Conclusion { get; set; }
        public string AzistaRepresentative { get; set; }
    }
}
