//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubsystemHistory
    {
        public int ID { get; set; }
        public Nullable<int> GeneralInformationID { get; set; }
        public string StationID { get; set; }
        public string ParameterID { get; set; }
        public string Parmaeter { get; set; }
        public string SerialNo { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
