//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NHPQualityAWS
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string time { get; set; }
        public string GPRS_Battery_Voltage { get; set; }
        public string INSAT_Battery_Voltage { get; set; }
        public string GPRS_Hourly_Rainfall { get; set; }
        public string INSAT_Hourly_Rainfall { get; set; }
        public string GPRS_Daily_Rain { get; set; }
        public string INSAT_Daily_Rain { get; set; }
        public string GPRS_Air_Temperature { get; set; }
        public string INSAT_Air_Temperature { get; set; }
        public string GPRS_Evaporation { get; set; }
        public string INSAT_Evaporation { get; set; }
        public string GPRS_Wind_Speed { get; set; }
        public string INSAT_Wind_Speed { get; set; }
        public string GPRS_Wind_Direction { get; set; }
        public string INSAT_Wind_Direction { get; set; }
        public string GPRS_Atmospheric_Pressure { get; set; }
        public string INSAT_Atmospheric_Pressure { get; set; }
        public string GPRS_Relative_Humidity { get; set; }
        public string INSAT_Relative_Humidity { get; set; }
        public string GPRS_Solar_Radiation { get; set; }
        public string INSAT_Solar_Radiation { get; set; }
        public string GPRS_Water_Level { get; set; }
        public string INSAT_Water_Level { get; set; }
    }
}
