//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_00034
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string Pressure { get; set; }
        public string Internal_Temperature { get; set; }
        public string Latitude { get; set; }
        public string Latitude_Unit { get; set; }
        public string Longitude { get; set; }
        public string Longitude_Unit { get; set; }
        public string Satellites { get; set; }
        public string Altitude { get; set; }
        public string Altitude_Unit { get; set; }
        public string Heading { get; set; }
        public string Heading_Unit { get; set; }
        public string Speed { get; set; }
        public string Speed_Unit { get; set; }
        public string Dew_Point { get; set; }
        public string Derieved_Pressure { get; set; }
        public string Created_Date { get; set; }
    }
}
