//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationMaster_
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string TehsilTaluk { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Bank { get; set; }
        public string BusStand { get; set; }
        public string RailwayStation { get; set; }
        public string Airport { get; set; }
        public string OtherInformation { get; set; }
        public Nullable<int> StationCategoryID { get; set; }
        public string Profile { get; set; }
        public string Gain { get; set; }
        public string Offset { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string StationID { get; set; }
        public string SerialNumber { get; set; }
        public string ShowInGraph { get; set; }
        public string ShowInGrid { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
    }
}
