//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteVisit2_SubObservationAWSMaster
    {
        public int ID { get; set; }
        public Nullable<int> ObservationID { get; set; }
        public string MaterialDescription { get; set; }
    }
}
