//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VMCAjwaDataReport
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Battery_Voltage_V_ { get; set; }
        public string C15mins_RAINFALL_mm_ { get; set; }
        public string Daily_Rain_mm_ { get; set; }
        public string Air_Temperature_C_ { get; set; }
        public string Wind_Speed_m_s_ { get; set; }
        public string Wind_Direction_DEG_ { get; set; }
        public string Atmospheric_Pressure_hPa_ { get; set; }
        public string Humidity___ { get; set; }
        public string Dew_Point__C_ { get; set; }
        public string Wind_Run_m_ { get; set; }
        public string Wind_Chill_kgcal_m2_h_ { get; set; }
        public string Heat_Index__C_ { get; set; }
        public string THW_Index__C_ { get; set; }
        public string Rain_Rate_mm_hr_ { get; set; }
        public string High_Speed_m_s_ { get; set; }
        public string High_Direction_Deg_ { get; set; }
    }
}
