//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StationData_00553
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string StationID { get; set; }
        public string Atmospheric_pressure { get; set; }
        public string Air_temperature_max { get; set; }
        public string Air_temperature_min { get; set; }
        public string Air_temperature { get; set; }
        public string Battery_voltage { get; set; }
        public string Hourly_Rain { get; set; }
        public string SNOW_PRECIPITATION { get; set; }
        public string PYRGEOMETER_IN { get; set; }
        public string PYRGEOMETER_OUT { get; set; }
        public string PYRGEOMETER_BODY_TEMPERATURE { get; set; }
        public string RADIATION_IN { get; set; }
        public string RADIATION_OUT { get; set; }
        public string SUN_DURATION { get; set; }
        public string RELATIVE_HUMIDITY { get; set; }
        public string IRST { get; set; }
        public string WIND_DIRECTION { get; set; }
        public string WIND_SPEED { get; set; }
        public string NET_RADIAITION { get; set; }
        public string SNOW_DEPTH { get; set; }
        public string Status { get; set; }
        public string Created_Date { get; set; }
    }
}
