//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SitePhotographs
    {
        public int ID { get; set; }
        public string StationName { get; set; }
        public string StationID { get; set; }
        public string Step1 { get; set; }
        public string Step2 { get; set; }
        public string Step3 { get; set; }
        public string Step4 { get; set; }
        public string Step5 { get; set; }
        public string Step6 { get; set; }
        public string Step7 { get; set; }
        public string Step8 { get; set; }
        public string Step9 { get; set; }
        public string Step10 { get; set; }
        public string Step11 { get; set; }
        public string Step12 { get; set; }
        public string Step13 { get; set; }
        public string Step14 { get; set; }
        public string Step15 { get; set; }
        public string Step16 { get; set; }
        public string Step17 { get; set; }
        public string Step18 { get; set; }
        public string Step19 { get; set; }
        public string Step20 { get; set; }
        public string Step21 { get; set; }
        public string Step22 { get; set; }
    }
}
