//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trgDemoMst_DV
    {
        public int TrgId { get; set; }
        public Nullable<int> DataId { get; set; }
        public string StationId { get; set; }
        public Nullable<System.DateTime> BurstDate { get; set; }
        public Nullable<System.TimeSpan> BurstTime { get; set; }
        public Nullable<System.DateTime> InsertedDateTime { get; set; }
    }
}
